### ISSUE TITLE
dapp update does not install latest dependancies

### ISSUE THREAD

**Issue by NiklasKunkel** [dapphub/dapp#38]
`dapp update ds-test`
`+ git submodule update --init --recursive lib/ds-test`

Does not install the latest version of ds-test.

**Comment by dbrock** [comment]
So `dapp update` just updates your working directory, whereas `dapp upgrade` upgrades to the latest version (and commits the change to git).

Confusing, I know, but at the same time somewhat standard usage (e.g. `apt update` vs `apt upgrade` is a similar distinction).

In other words `dapp update` just makes it so that your working directory has the right versions checked out. This can be needed after for example switching between branches or after doing a `git pull`.
