### ISSUE TITLE
dapp create errors when contract in src/subdir

### ISSUE THREAD

**Issue by travs** [dapphub/dapp#62]
Calling something like:

```sh
# dapp create SimpleMarket --from $ADDRESS_1                   # this can't find anything
dapp create exchange/thirdparty/SimpleMarket --from $ADDRESS_1 # this is my 2nd guess
```

gives:

```sh
+ seth send --create out/exchange/thirdparty/SimpleMarket.bin 'exchange/thirdparty/SimpleMarket
()' --from 0x0015248b433a62fb2d17e19163449616510926b6                                          
seth-send: warning: `ETH_GAS' not set; using default gas amount                                
<stdin>:1:55: Error: Expected token LParen got 'Div'                                           
pragma solidity ^0.4.8; contract A { function exchange/thirdparty/SimpleMarket() public; } 
```
which seems to be due to the `/` delimiter.
My first guess is to do something like [this](https://github.com/dapphub/dapp/blob/master/libexec/dapp/dapp-build#L26-L34), and `find` the contract by its filename. Does this make sense?

**Comment by dbrock** [comment]
Interesting, I guess nobody ever tried creating a contract in a subdirectory.

But I think the solution here is actually much simpler. The only problem is that `exchange/thirdparty/SimpleMarket()` needs to be truncated to just `SimpleMarket()`.

Should be fixed by a2b998c8f6404d8cd85cef4c0e9c83b2722ce70b.
